apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
#    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: distributed.orders
      http:
        paths:
#          - path: /orderList
#            pathType: Prefix
#            backend:
#              service:
#                name: orderlist-cluster-ip-service
#                port:
#                  number: 6001
#          - path: /orderManagement
#            pathType: Prefix
#            backend:
#              service:
#                name: ordermanagement-cluster-ip-service
#                port:
#                  number: 6002
#          - path: /productList
          - path: /productInventory
            pathType: Prefix
            backend:
              service:
                name: product-inventory-cluster-ip-service
                port: 
                  number: 6003          