name: distributed_orders_flutter
description: Distributed Orders

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 3.0.10
  get_it: 5.0.1
  flutter_guid: 0.1.0
  logger: 0.9.4
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
