name: distributed_orders_flutter
description: Distributed Orders

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 3.0.10
  get_it: 5.0.1
  flutter_guid: 0.1.0
  logger: 0.9.4
  json_annotation: 3.1.0
  mobx: 1.2.1+3
  flutter_mobx: 1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.2
  json_serializable: 3.5.0
  mobx_codegen: 1.1.1+1

flutter:

  uses-material-design: true
